---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: stretch
    box: bento/debian-9.0
    interfaces:
      - network_name: private_network
        type: static
        auto_config: false
        ip: 10.99.0.2
  - name: xenial
    box: bento/ubuntu-16.04
    interfaces:
      - network_name: private_network
        type: static
        auto_config: false
        ip: 10.99.0.3
provisioner:
  name: ansible
  connection_options:
    ansible_become: yes
  lint:
    name: ansible-lint
scenario:
  name: install
verifier:
  name: testinfra
  lint:
    name: flake8
